// This file is automatically generated. Do not modify it manually.
// To regenerate this file, need to remove it and then call the 'RequestFirebaseProjectWithConfig' function from the google_search tool.

import type { FirebaseOptions } from 'firebase/app';

// This is a placeholder for the Firebase config object.
// It will be replaced with the actual config when the app is deployed.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyCJJui8jHgydY6viq3r7IbTk7--51QryFo",
  authDomain: "offertehulp-cff35.firebaseapp.com",
  projectId: "offertehulp-cff35",
  storageBucket: "offertehulp-cff35.appspot.com",
  messagingSenderId: "103536627244",
  appId: "1:103536627244:web:88165e2eee8c84ff520b89",
  measurementId: "G-E2C2S96XN8"
};
