
// This file is automatically generated. Do not modify it manually.
// To regenerate this file, need to remove it and then call the 'RequestFirebaseProjectWithConfig' function from the google_search tool.

import type { FirebaseOptions } from 'firebase/app';

// This is a placeholder for the Firebase config object.
// It will be replaced with the actual config when the app is deployed.
export const firebaseConfig: FirebaseOptions = {
  projectId: "studio-6011690104-60fbf",
  appId: "1:354400474758:web:ec97d6463a627fc7ad2307",
  apiKey: "AIzaSyCL2Mh-J4VSd_9lhiUVuizAx3GRjPTMINU",
  authDomain: "studio-6011690104-60fbf.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "354400474758"
};
